### ISSUE TITLE
Morning session: Peer to peer review

### ISSUE THREAD

**Issue by bamsi** [jasonfelice/Leaderboard#4]
Hello!
Good job so far 👍 . Your design meets the requirements perfectly! However, you may work on the following optional changes to improve your project:

1. It could be better if you use more semantic tags like `section`, and `header `instead of `div `in your HTML index page
2. Please use the async function when communicating with the APIs, refer to your `postScore()` function. 
3. Please use one function inside the other because the two functions are dependent
    https://github.com/jasonfelice/Leaderboard/blob/8840c7fae724a5c535d59ac21f25575b66fe5f5e/src/modules/app.js#L43-L50

**Happy coding 🥇**

**Comment by jasonfelice** [comment]
I've made the changes you mentioned above.
Thanks a lot for taking the time to review my code.
